# Change these first
owner: DfE-Digital # Your GitHub organization or username, where this repository lives
repo: find-and-use-an-api-upptime # The name of this repository

sites:
  - name: Find and Use an API Consumption Portal - PROD
    url: https://beta-find-and-use-an-api.education.gov.uk
  - name: Find and Use an API Management Portal - PROD
    url: https://apimanagement.education.gov.uk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /find-and-use-an-api-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Find and Use an API service status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a test
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
