# Change these first
owner: DfE-Digital # Your GitHub organization or username, where this repository lives
repo: find-and-use-an-api-upptime # The name of this repository

sites:
  - name: Consumption Portal - PROD
    url: https://beta-find-and-use-an-api.education.gov.uk
  - name: Management Portal - PROD
    url: https://apimanagement.education.gov.uk
  - name: Management API - PROD
    url: https://apimanagement.education.gov.uk/api/tasks/apis
    method: GET
    headers:
      - "Authorization: Bearer $MANAGEMENT_PROD_API_KEY"
  - name: Demo Workspace API - PROD
    url: https://api.education.gov.uk/example/getInformation
    method: GET
    headers:
      - "subscription-key: $DEMO_WORKSPACE_API_KEY_PROD"
  - name: Consumption Portal - PRE-PROD
    url: https://pp-find-and-use-an-api.education.gov.uk
  - name: Management Portal - PRE-PROD
    url: https://pp-apimanagement.education.gov.uk
  - name: Management API - PRE-PROD
    url: https://pp-apimanagement.education.gov.uk/api/tasks/apis
    method: GET
    headers:
      - "Authorization: Bearer $MANAGEMENT_PREPROD_API_KEY"
  - name: Demo Workspace API - Pre-PROD
    url: https://pp-api.education.gov.uk/example/getInformation
    method: GET
    headers:
      - "subscription-key: $DEMO_WORKSPACE_API_KEY_PREPROD"
  - name: Consumption Portal - TEST
    url: https://test-find-and-use-an-api.education.gov.uk
  - name: Management Portal - TEST
    url: https://test-apimanagement.education.gov.uk
  - name: Management API - TEST
    url: https://test-apimanagement.education.gov.uk/api/tasks/apis
    method: GET
    headers:
      - "Authorization: Bearer $MANAGEMENT_TEST_API_KEY"
  - name: Demo Workspace API - TEST
    url: https://test-api.education.gov.uk/example/getInformation
    method: GET
    headers:
      - "subscription-key: $DEMO_WORKSPACE_API_KEY_TEST"
  - name: Consumption Portal - DEV
    url: https://dev-find-and-use-an-api.education.gov.uk
  - name: Management Portal - DEV
    url: https://dev-apimanagement.education.gov.uk
  - name: Management API - DEV
    url: https://dev-apimanagement.education.gov.uk/api/tasks/apis
    method: GET
    headers:
      - "Authorization: Bearer ${{ secrets.MANAGEMENT_DEV_API_KEY }}"
  - name: Demo Workspace API - DEV
    url: https://dev-api.education.gov.uk/example/getInformation?subscription-key=$DEMO_WORKSPACE_API_KEY_DEV
    method: GET
      

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /find-and-use-an-api-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Find and Use an API service status
  introTitle: "**Find and Use an API** provides a GOV.UK branded public facing front door for users to discover and consume data from DfE APIs."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
